### ISSUE TITLE
Does not support django 3.0?

### ISSUE THREAD

**Issue by leekyuchang** [thornomad/django-hitcount#87] opened 2020-01-02 16:19 UTC
Does not support django 3.0?

**Comment by vinpalace** [comment] 2020-02-12 08:45
Yea it throws error, 

`  File "/Users/vineeth/envs/codingpupv2/lib/python3.7/site-packages/hitcount/models.py", line 10, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/Users/vineeth/envs/codingpupv2/lib/python3.7/site-packages/django/utils/encoding.py)`

**Comment by bmull** [comment] 2020-02-28 02:49
This is a duplicate of #86.

**Comment by bashu** [comment] 2020-04-30 05:04
fixed in 1.3.2

**Closed by bashu** 2020-04-30 05:04 UTC
